version: "2.3"

services:
  users:
    build: .
    container_name: users
    ports:
      - 9001:9000
    volumes:
      - "./service/user:/service"
    command: >
      bash -c "npm install && npm run start:user"
  vehicles:
    build: .
    container_name: vehicles
    ports:
      - 9002:9000
    volumes:
      - "./service/vehicle:/service"
    command: >
      bash -c "npm install && npm run start:vehicle"
  crawlers:
    build: .
    container_name: crawlers
    ports:
      - 9003:9000
    volumes:
      - "./service/crawler:/service"
    command: >
      bash -c "npm install && npm run start:crawler"